version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: certificate-app-php
    container_name: certificate_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - PHP_IDE_CONFIG=serverName=certificate-app
    depends_on:
      - db
    command: sh -lc "composer install --no-interaction --prefer-dist --no-scripts && php-fpm"

  web:
    image: nginx:1.25-alpine
    container_name: certificate_web
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: certificate_db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


